services:
  excel-tool-jupyter:
    build: .
    container_name: excel-tool-jupyter
    restart: unless-stopped

    ports:
      - "127.0.0.1:8008:8008"

    environment:
      - PYTHONUNBUFFERED=1

    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
